import type { ConfigContext, ExpoConfig } from "expo/config";

/**
 * Junket iOS app config.
 *
 * Continuous Native Generation: the `ios/` project is generated by
 * `expo prebuild` (locally or in CI) and is never committed.
 *
 * CI / environment overrides:
 * - JUNKET_IOS_BUNDLE_ID    — Apple bundle identifier (must match the
 *   provisioning profile used to sign release builds).
 * - JUNKET_IOS_BUILD_NUMBER — CFBundleVersion; unique per TestFlight upload.
 * - EXPO_PUBLIC_API_URL    — API base URL baked into the JS bundle
 *   (see src/config.ts for defaults).
 */
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: "Junket",
  slug: "junket",
  version: "1.0.0",
  orientation: "portrait",
  icon: "./assets/images/icon.png",
  scheme: "junket",
  userInterfaceStyle: "dark",
  backgroundColor: "#090b09",
  ios: {
    bundleIdentifier: process.env.JUNKET_IOS_BUNDLE_ID ?? "com.joelyoung.junket",
    buildNumber: process.env.JUNKET_IOS_BUILD_NUMBER ?? "1",
    supportsTablet: false,
    // Sign in with Apple entitlement (the App ID must have the capability
    // enabled in the Apple Developer portal).
    usesAppleSignIn: true,
    config: {
      usesNonExemptEncryption: false,
    },
  },
  web: {
    output: "static",
    favicon: "./assets/images/favicon.png",
  },
  plugins: [
    "expo-router",
    [
      "expo-splash-screen",
      {
        backgroundColor: "#090b09",
        image: "./assets/images/splash-icon.png",
        imageWidth: 120,
      },
    ],
    "expo-secure-store",
    [
      "expo-image-picker",
      {
        photosPermission:
          "Junket uses your photo library so you can pick recipe cover photos.",
        cameraPermission: "Junket uses your camera so you can photograph recipes.",
      },
    ],
    "expo-apple-authentication",
    [
      "expo-local-authentication",
      {
        faceIDPermission: "Junket uses Face ID to unlock the app.",
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
});
