name: Continuous Integration / Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  BuildApp:
    uses: ./.github/workflows/BuildApp.yml
    with:
      image_name: recipe-db
    secrets:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

  DeployApp:
    needs: BuildApp
    uses: JoelYoung01/Templates/.github/workflows/DeployWebhook.yaml@v0.1.2
    with:
      app_name: Atmosphyr
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
