name: Continuous Integration / Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  BuildApp:
    uses: ./.github/workflows/BuildApp.yml
    with:
      image_name: recipe-db
    secrets:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
