name: Manual Deployment
run-name: Manual Deployment started by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Name Of Image"
        required: false
        default: "RecipeDB"

jobs:
  BuildApp:
    uses: ./.github/workflows/BuildApp.yml
    with:
      image_name: ${{ inputs.image_name }}
    secrets:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
